[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
extend-select = [
  "E", "F", "B", "I", "UP", "SIM", "A", "TID", "N", "TCH"
]
ignore = ["B008", "E501"]

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
