#!/usr/bin/env sh

sudo yabai --load-sa

yabai -m config layout bsp

yabai -m config window_placement second_child

yabai -m config mouse_follows_focus on

yabai -m rule --add app="^Arc$" manage=on
yabai -m rule --add app="^Ghostty$" manage=on

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Prime Video$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off

yabai -m rule --add app="^Code$" space=^3
yabai -m rule --add app="^Ghostty$" space=^2
yabai -m rule --add app="^Arc$" space=^1
yabai -m rule --add app="^TickTick$" space=^4

